### ISSUE TITLE
vers port

### ISSUE THREAD

**Issue by faassen** [ajalab/fm-index#17]
Thank you very much for this crate. Today I spent some time porting it from fid to the [vers-vecs](https://github.com/Cydhra/vers) implementation of rank and select, as well as its wavelet matrix implementation. I did this in the hope of a performance benefit, and because I was using vers already. 

Here it is:

https://github.com/faassen/fm-index/tree/vers

It resulted in a very nice speed uplift in the benchmarks, as you can see here:

https://github.com/Cydhra/vers/issues/17

I'm planning to release this as `fm-index-vers` eventually. I will of course be sure to credit you! I'm also open to merging it into this repository instead, but it's a fundamental change in dependencies and I'm not sure whether you want to maintain this.

**Comment by faassen** [comment]
Oh, I had seen your emoji reactions, then went happily to prepare stuff for release, and missed your comment until I came back to report that I made a release! It's here:

https://crates.io/crates/fm-index-vers

and in this repository:

https://github.com/faassen/fm-index-vers

If you want to take a look at my PR, that'd be great. If it turns out you accept it, we can consolidate things into fm-index and I'll retire fm-index-vers again. I'll send the raw PR which includes readme changes we want to modify, so you can take a look at the code differences.

**Comment by ajalab** [comment]
We ported this crate from [fid](https://github.com/ajalab/fid) to [vers](https://github.com/Cydhra/vers) in #18, and released a new version [0.2.0](https://crates.io/crates/fm-index).
